### ISSUE TITLE
Add ability to filter distros by characteristic ( e.g. only show systemd-free distros or rolling release distros)

### ISSUE THREAD

**Issue by andrew712-1** [ulosino/ulosino#22]

**Comment by fernpolo** [comment]
Hey there,

The new 1.1.0 update implements new search bars where one can search by desktop, platform, etc. It's available through the Browse page.

This was a quick fix and doesn't filter the list or exclude any distributions. I'm still investigating an implementation for that, which might take some more time.

When the linked PR is merged, it appears that it will close this issue. Feel free to reopen it if you wish.
